/**
 * Generate the launcher and notification icons from the official whale mark.
 *
 *   node tools/make-icon.mjs
 *
 * ## Why this is generated rather than hand-written
 *
 * The mark is 3448 characters of path data. Pasting that into an XML file by hand
 * is a transcription exercise with no upside — one dropped digit gives a subtly
 * wrong animal and nothing would report it. The path lives in tools/whale-path.txt
 * exactly as it was extracted, and this turns it into a vector drawable, so the
 * icon can be regenerated and reviewed.
 *
 * Provenance: the path was read out of the running client's own DOM (the single
 * path in the svg with viewBox "0 0 23.16 17.04"), which is the authentic mark
 * rather than a redrawing of it.
 *
 * ## Two files, for two different jobs
 *
 * The launcher icon is an **opaque tile** with the mark on it. The status-bar icon
 * cannot be that: Android renders a notification's small icon as a *mask*, turning
 * every non-transparent pixel into one flat colour, so an opaque tile arrives as a
 * solid white square. The notification icon is therefore the mark alone, sized to
 * sit inside the 22dp safe area of a 24dp canvas, with no background at all.
 *
 * @module pulse-android/tools/make-icon
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

/** The canvas every launcher icon is drawn on. */
const SIZE = 108;
/** How much of that canvas the mark itself takes. */
const MARK_WIDTH = 84;
/** The status-bar canvas, and how much of it the mark takes (inside the safe area). */
const NOTIFICATION_SIZE = 24;
const NOTIFICATION_MARK_WIDTH = 20;
/** The mark's own coordinate space, from the extracted viewBox. */
const MARK_BOX = { width: 23.16, height: 17.04 };

const path = readFileSync(join(here, 'whale-path.txt'), 'utf8').trim();
if (!/^M[\d.\s-]+/.test(path)) {
  throw new Error(`whale-path.txt does not look like path data: ${path.slice(0, 40)}`);
}
if (path.includes('"') || path.includes('<')) {
  throw new Error('path data contains markup characters and cannot be embedded');
}

const round = value => Number(value.toFixed(3));

/**
 * Scale and centre the mark on a square canvas.
 *
 * @param {number} canvas - the viewport size.
 * @param {number} markWidth - how wide the mark should be on it.
 * @returns {{scale: number, offsetX: number, offsetY: number, height: number}} placement.
 */
function place(canvas, markWidth) {
  const scale = markWidth / MARK_BOX.width;
  const height = MARK_BOX.height * scale;
  return {
    scale: round(scale),
    offsetX: round((canvas - markWidth) / 2),
    offsetY: round((canvas - height) / 2),
    height: round(height),
  };
}

const launcher = place(SIZE, MARK_WIDTH);
const launcherXml = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by tools/make-icon.mjs from tools/whale-path.txt — do not edit by hand.
  The mark is the official one, extracted from the running client, drawn black on a
  white tile so it reads on a light or a dark wallpaper.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${SIZE}dp"
    android:height="${SIZE}dp"
    android:viewportWidth="${SIZE}"
    android:viewportHeight="${SIZE}">

    <path
        android:fillColor="#FFFFFF"
        android:pathData="M18,4 L90,4 A14,14 0 0 1 104,18 L104,90 A14,14 0 0 1 90,104 L18,104 A14,14 0 0 1 4,90 L4,18 A14,14 0 0 1 18,4 Z" />

    <group
        android:translateX="${launcher.offsetX}"
        android:translateY="${launcher.offsetY}"
        android:scaleX="${launcher.scale}"
        android:scaleY="${launcher.scale}">
        <path
            android:fillColor="#111111"
            android:pathData="${path}" />
    </group>
</vector>
`;

const notification = place(NOTIFICATION_SIZE, NOTIFICATION_MARK_WIDTH);
const notificationXml = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by tools/make-icon.mjs from tools/whale-path.txt — do not edit by hand.

  The status-bar icon, deliberately a different drawing from the launcher icon:
  Android renders a notification's small icon as a mask, painting every
  non-transparent pixel one flat colour. The launcher icon is an opaque rounded tile,
  so it would arrive here as a solid white square. This is the whale alone, white on
  nothing, inside the 22dp safe area the system may otherwise crop.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${NOTIFICATION_SIZE}dp"
    android:height="${NOTIFICATION_SIZE}dp"
    android:viewportWidth="${NOTIFICATION_SIZE}"
    android:viewportHeight="${NOTIFICATION_SIZE}">

    <group
        android:translateX="${notification.offsetX}"
        android:translateY="${notification.offsetY}"
        android:scaleX="${notification.scale}"
        android:scaleY="${notification.scale}">
        <path
            android:fillColor="#FFFFFFFF"
            android:pathData="${path}" />
    </group>
</vector>
`;

for (const [target, body, note] of [
  [join(root, 'app', 'res', 'drawable', 'ic_launcher.xml'), launcherXml,
    `画布 ${SIZE}x${SIZE}，标志 ${round(MARK_WIDTH)}x${launcher.height}，`
    + `偏移 ${launcher.offsetX},${launcher.offsetY}，缩放 ${launcher.scale}`],
  [join(root, 'app', 'res', 'drawable', 'ic_notification.xml'), notificationXml,
    `画布 ${NOTIFICATION_SIZE}x${NOTIFICATION_SIZE}，标志 ${round(NOTIFICATION_MARK_WIDTH)}x${notification.height}，`
    + `偏移 ${notification.offsetX},${notification.offsetY}，缩放 ${notification.scale}`],
]) {
  writeFileSync(target, body, 'utf8');
  console.log(`已生成 ${target}`);
  console.log(`  ${note}`);
}
